# Generated by Django 3.1.3 on 2020-12-04 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='full_description',
            field=models.TextField(blank=True),
        ),
    ]
