# Generated by Django 3.1.3 on 2020-12-04 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_project_full_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tech',
            field=models.TextField(blank=True),
        ),
    ]
