# Generated by Django 3.1.3 on 2020-12-04 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_project_tech'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image_main',
        ),
        migrations.AddField(
            model_name='project',
            name='image_1',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.AddField(
            model_name='project',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='portfolio/images/'),
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
